spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/new_schema
    username: root
    password: root

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8081
